apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: {ASO Resource Group Name} 
  namespace: my-app
spec:
  location: {Location}
  azureName: {ASO Resource Group Name} 
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: DatabaseAccount
metadata:
  name: {Cosmos DB Account Name}
  namespace: my-app
spec:
  location: {Location}  
  owner:
    name: {ASO Resource Group Name} 
  kind: GlobalDocumentDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: {Location}
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: SqlDatabase
metadata:
  name: todoapp
  namespace: my-app
spec:
  location: {Location}
  owner:
    name: {Cosmos DB Account Name}
  options:
    throughput: 400
  resource:
    id: todoapp
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: SqlDatabaseContainer
metadata:
  name: tasks
  namespace: my-app
spec:
  location: {Location}
  owner:
    name: todoapp
  resource:
    id: tasks
    partitionKey:
      kind: Hash
      paths: ["/id"]