<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>385e43af-3751-4085-aceb-c670a91751dd</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.2" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.11.2" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.63.2" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.16.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.16.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
