version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "nuget"
    directory: "/Application"
    groups:
      nuget:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/Application"
    groups:
      docker:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "terraform"
    directory: "/Terraform"
    groups:
      terraform:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
